// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXDn3lRUvjbHYyWz4niw0MzEs8K68NH30',
    appId: '1:1013855023708:web:7d2c2e6b92bf468e73ec99',
    messagingSenderId: '1013855023708',
    projectId: 'login-64f7d',
    authDomain: 'login-64f7d.firebaseapp.com',
    storageBucket: 'login-64f7d.appspot.com',
    measurementId: 'G-BRVWXHSKKS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbZF72mTFwnwaQa-rD1950Yombmu8PRX4',
    appId: '1:1013855023708:android:de3d2fde56788ed173ec99',
    messagingSenderId: '1013855023708',
    projectId: 'login-64f7d',
    storageBucket: 'login-64f7d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBl8u7DPJaE5f7cgkZmHt0gT6vyQb-FvGs',
    appId: '1:1013855023708:ios:f61d1431c02b0ef673ec99',
    messagingSenderId: '1013855023708',
    projectId: 'login-64f7d',
    storageBucket: 'login-64f7d.appspot.com',
    iosBundleId: 'com.example.loginFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBl8u7DPJaE5f7cgkZmHt0gT6vyQb-FvGs',
    appId: '1:1013855023708:ios:6c8d2f5fdbbdfa1773ec99',
    messagingSenderId: '1013855023708',
    projectId: 'login-64f7d',
    storageBucket: 'login-64f7d.appspot.com',
    iosBundleId: 'com.example.loginFirebase.RunnerTests',
  );
}
